// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuky6_RTP5qI5WBYflYxsS4ZQIpOYHW2s',
    appId: '1:360570170039:web:20011b648b38c18a813b32',
    messagingSenderId: '360570170039',
    projectId: 'timeshare-32d37',
    authDomain: 'timeshare-32d37.firebaseapp.com',
    storageBucket: 'timeshare-32d37.firebasestorage.app',
    measurementId: 'G-6ZNCSHKFY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJgUlNUy__onEuKO3sHwaPIooCL_GIxVI',
    appId: '1:360570170039:android:97b750739af5ef8d813b32',
    messagingSenderId: '360570170039',
    projectId: 'timeshare-32d37',
    storageBucket: 'timeshare-32d37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-6mGhbmk10Lca97mjVQLyZmWBaR2d_OQ',
    appId: '1:360570170039:ios:fabedd3252ef901e813b32',
    messagingSenderId: '360570170039',
    projectId: 'timeshare-32d37',
    storageBucket: 'timeshare-32d37.firebasestorage.app',
    iosClientId:
        '360570170039-fjlr1os90jd7rue6s96bhccgphv1ea2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-6mGhbmk10Lca97mjVQLyZmWBaR2d_OQ',
    appId: '1:360570170039:ios:fabedd3252ef901e813b32',
    messagingSenderId: '360570170039',
    projectId: 'timeshare-32d37',
    storageBucket: 'timeshare-32d37.firebasestorage.app',
    iosClientId:
        '360570170039-fjlr1os90jd7rue6s96bhccgphv1ea2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuky6_RTP5qI5WBYflYxsS4ZQIpOYHW2s',
    appId: '1:360570170039:web:48e7d2847c2001a4813b32',
    messagingSenderId: '360570170039',
    projectId: 'timeshare-32d37',
    authDomain: 'timeshare-32d37.firebaseapp.com',
    storageBucket: 'timeshare-32d37.firebasestorage.app',
    measurementId: 'G-T7YY14C7B0',
  );
}

